### ISSUE TITLE
Look at this test... It is really rare

### ISSUE THREAD

**Issue by cpfarher** [celluloid/timers#44]
The following code has unexpected result. When execute this script, and sleep_time(4 to 0 with 0.5 step) <  scan (3 seconds), it takes a wrong diff time...

require 'timers'

timers_scan = Timers::Group.new
scan=[3.0]
scan_started=[]

sleep_time=4.0
last_time=Time.now.to_f
loop {

  scan.each do |v|
    #if timers_scan.all? { |timer| timer.interval!=v }

```
if !scan_started.include? v
  scan_started<<v
  timers_scan.every(v) do
      sleep(sleep_time)
      puts "SCAN #{v} segundos - #{Time.now.to_f-last_time} -- #{sleep_time} s.".red
      sleep_time=sleep_time-0.5 unless sleep_time==0
      last_time=Time.now.to_f
  end
end
```

  end

timers_scan.wait
}

SCAN 3.0 segundos - 7.000695466995239 -- 4.0 s.
SCAN 3.0 segundos - 2.9999730587005615 -- 3.5 s.
SCAN 3.0 segundos - 2.4998843669891357 -- 3.0 s.
SCAN 3.0 segundos - 2.500093698501587 -- 2.5 s.
SCAN 3.0 segundos - 2.4998972415924072 -- 2.0 s.
SCAN 3.0 segundos - 2.00003981590271 -- 1.5 s.
SCAN 3.0 segundos - 2.499767303466797 -- 1.0 s.
SCAN 3.0 segundos - 2.4998912811279297 -- 0.5 s.
SCAN 3.0 segundos - 2.5001723766326904 -- 0.0 s.
SCAN 3.0 segundos - 2.9999217987060547 -- 0.0 s.
SCAN 3.0 segundos - 3.0002198219299316 -- 0.0 s.
SCAN 3.0 segundos - 2.9999282360076904 -- 0.0 s.
SCAN 3.0 segundos - 2.9997901916503906 -- 0.0 s.
SCAN 3.0 segundos - 3.000077962875366 -- 0.0 s.
SCAN 3.0 segundos - 3.000044107437134 -- 0.0 s.

Thank you....

**Comment by ioquatix** [comment]
Can you please put the code in a gist so I can run it.

**Comment by cpfarher** [comment]
sure.... Here you are:

https://gist.github.com/cpfarher/9bc88feb0bbb8451abae

**Comment by tarcieri** [comment]
Please reopen if this is still a problem
