### ISSUE TITLE
Using Redis On Message Event to Reset Timers

### ISSUE THREAD

**Issue by jmwright** [celluloid/timers#48]
I've got a Redis subscription, which blocks, and I'm also using timers.wait, which also blocks. I'm not sure how to make them work together. I've got the timers.wait loop inside a Thread.new block, but the timers will stop running periodically. I'm sure that's not the right way to run it anyway.
```ruby
@@timers = Timers::Group.new
...
Thread.new {
  loop { @@timers.wait }
}
```
Essentially what I'm trying to do is reset the timers based on events triggered by messages coming through Redis. Can you point me in the right direction on how to do this?

**Comment by digitalextremist** [comment]
@jmwright generally this sort of thing we readily answer here:

* https://groups.google.com/forum/#!forum/celluloid-ruby

But I'll leave this up and try to direct it to the best responders for when they have some time to reply:

/cc: @ioquatix, @tarcieri

**Comment by jmwright** [comment]
@digitalextremist Ok, thank you.

**Comment by ioquatix** [comment]
Timers::Group is exclusive. The simplest way to combine this with redis might be to provide a timeout to wait, e.g. 

```
# Wait for the next timer and fire it. Can take a block, which should behave
    # like sleep(n), except that n may be nil (sleep forever) or a negative
    # number (fire immediately after return).
    def wait(&block)
    ....


@@timers = Timers::Group.new

@@timers.wait do |timeout|
  redis.wait_for_messages(timeout)
end
```


.. or something like that.

**Comment by ioquatix** [comment]
IF you have further questions please don't hesitate to reopen this issue.

**Comment by tarcieri** [comment]
You can also use `Timers::Group#wait_interval` to calculate the interval to wait until the next timer fires:

https://github.com/celluloid/timers/blob/master/lib/timers/group.rb#L72

Pretty much the same thing @ioquatix just said, just without using a block

**Comment by jmwright** [comment]
Great, thank you.
