### ISSUE TITLE
undefined method `now_and_every'

### ISSUE THREAD

**Issue by midas643** [celluloid/timers#50]
I get undefined method `now_and_every' for #<Timers::Group:0x89c3378> (NoMethodError) on windows and on linux. I have to manually replace installed lib directory with one from this repo to get rid of this error. What's the cause of it? Thanks in adv.

**Comment by digitalextremist** [comment]
What `gem` version or branch commit? It might be that we need to cut a new gem.

**Comment by blackdev1l** [comment]
:+1:  found out this error right now, wonder if i can do the same thing just with `every`

**Comment by digitalextremist** [comment]
If you set an `every` timer, you can immediately issue `.trigger` on it to accomplish `now_and_every` without the method.

**Comment by blackdev1l** [comment]
Will do, thank you!

**Comment by midas643** [comment]
undefined method `trigger' for #<Timers::Timer:0x199e3c0> (NoMethodError)
Well... for me it didn't solve the issue.

I use rubygems 2.4.8 on windows and 2.4.6 on linux it's kinda weird. Thank you for your help.

**Comment by AlainPilon** [comment]
When is the next version of the gem (including now_and_every) going to be released?

**Comment by digitalextremist** [comment]
I'll drop in a point release today/tomorrow.

**Comment by AlainPilon** [comment]
Hi, I saw that you updated to 4.0.2 but ruby gem is still serving 4.0.1. any ETA for the official release?

**Comment by digitalextremist** [comment]
`4.0.2` has been cut and released on rubygems.
