### ISSUE TITLE
I want to cancel timer.wait from another thread, is this possible?

### ISSUE THREAD

**Issue by HongliYu** [celluloid/timers#55]
timers = Timers::Group.new
        five_second_timer = timers.after(10) { Thread.kill(runningThread) }
        runningThread = Thread.new do
          # this task cost me 5 seconds, then I want to cancel the timer from status of waiting ,is this possible?
        end
        timers.wait

**Comment by tarcieri** [comment]
The timers gem presently does not have cross-thread support. If you would like something like this, I would suggest using Celluloid

**Comment by ioquatix** [comment]
Perhaps you can explain a bit more what you are trying to achieve?

**Comment by digitalextremist** [comment]
And feel free to take this to the [Google Group](https://groups.google.com/forum/#!forum/celluloid-ruby) where we discuss things like this all the time.

**Comment by HongliYu** [comment]
Okay, I'll try Celluloid, thank you.@tarcieri
