### ISSUE TITLE
What's the right way to detach timers?

### ISSUE THREAD

**Issue by dblock** [celluloid/timers#59]
Looks like you have to block to run timers with `loop { timers.wait }` or similar. This is unlike in EventMachine where you can do a `EM.setup_periodic_timer { }` and it will go on do its thing. 

Maybe this should be documented more clearly (I'm happy to contribute)? How should you be detaching timers (thread?)?

**Comment by tarcieri** [comment]
Sounds like you want `#every`. Some docs here:

https://github.com/celluloid/celluloid/wiki/Timers

**Comment by dblock** [comment]
Right, that's what I use. But without blocking the calling thread the timers never run.

**Comment by tarcieri** [comment]
`loop { timers.wait }` is how to wait for the next timer to fire outside of Celluloid. They could probably use a `#run` method that wraps that up

**Comment by dblock** [comment]
That's confusing. I don't want to wait for the timer to fire, I just want to schedule and forget. Without the wait the timer never fires.

**Comment by dblock** [comment]
(and much thanks for replying @tarcieri)

**Comment by tarcieri** [comment]
If you want something to schedule the timers for you, use Celluloid

**Comment by dblock** [comment]
I guess I have more reading to do, I just expected it to work the same as in EventMachine :) I'll close this, thanks for your time.

**Comment by ioquatix** [comment]
@dblock This library is purely for implementing timers. It's not asynchronous as you seem to be expecting. As @tarcieri says, use Celluloid.
